name: auth_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: 4.6.1
  cloud_firestore: ^3.1.15
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  settings_ui: ^2.0.2
  google_fonts: ^2.3.1
  syncfusion_flutter_charts: ^20.1.56
  json_serializable: ^6.2.0
  getwidget: ^2.0.5
  get_it: ^7.2.0
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  new_gradient_app_bar: ^0.2.0
  email_validator: ^2.0.1
  fluttertoast: ^8.0.8
  flutter_hooks: ^0.18.4


  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:


    - assets/Picture.jpg
    - assets/Empty.jpg
    - assets/Card.jpg
    - assets/user.png
    - assets/Background.jpg
    - assets/Welcome.jpg
    - assets/Welcome2.jpg
    - assets/logo.png
    - assets/RoundLogo.png

    - assets/Cartes/Icon1.png
    - assets/Cartes/Icon2.png
    - assets/Cartes/Icon3.png
    - assets/Cartes/Icon4.png
    - assets/Cartes/Icon5.png
    - assets/Cartes/Icon6.png
    - assets/Cartes/Lassr.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
